
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc7_amd64_gcc530/src/SMPJ/AnalysisFW/src/SMPJAnalysisFW/a/SMPJAnalysisFW_xr.cc_tmp
 "LCGReflex/QCDMET",
 "LCGReflex/QCDJet",
 "LCGReflex/QCDPFJet",
 "LCGReflex/QCDPFJetBTag",
 "LCGReflex/QCDEventHdr",
 "LCGReflex/QCDEvent",
//--End   tmp/slc7_amd64_gcc530/src/SMPJ/AnalysisFW/src/SMPJAnalysisFW/a/SMPJAnalysisFW_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
